#+TITLE: Project in Statistics: Targeted Learning

Some of the material used in the course can be found here. 

* Data
The data we use can be retrieved by running the following commands in =R=, assuming you have
installed the =data.table= package.

#+BEGIN_SRC R
library(data.table)
pph <- fread("http://publicifsv.sund.ku.dk/~helene/pph-subset.csv")
#+END_SRC

*If you cannot load the data in this way, please write us immediately!*

* Note on influence functions and functional derivatives
We are working on a note that provides an introduction and motivation for studying semi-parametric
efficiency theory (i.e., targeted learning), which you can find [[./intro-eif-concepts.pdf][here]]. We have tried to collect some
of the theoretical results from the literature, and state the typically encountered definitions in a
mathematically precise way. You are not supposed to study everything in full detail, but should
instead consider the note as an additional service which might be helpful to you. Also, you are
/not/ supposed to write like this in you project! 
